/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHeaderToolbar {
        "backCallback": Function;
        "headerTitle": string;
        "showBack": boolean;
        "showClose": boolean;
        "showMenu": boolean;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ModalHeaderToolbar {
        "backCallback": Function;
        "headerTitle": string;
    }
}
declare global {
    interface HTMLAppHeaderToolbarElement extends Components.AppHeaderToolbar, HTMLStencilElement {
    }
    var HTMLAppHeaderToolbarElement: {
        prototype: HTMLAppHeaderToolbarElement;
        new (): HTMLAppHeaderToolbarElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLModalHeaderToolbarElement extends Components.ModalHeaderToolbar, HTMLStencilElement {
    }
    var HTMLModalHeaderToolbarElement: {
        prototype: HTMLModalHeaderToolbarElement;
        new (): HTMLModalHeaderToolbarElement;
    };
    interface HTMLElementTagNameMap {
        "app-header-toolbar": HTMLAppHeaderToolbarElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "modal-header-toolbar": HTMLModalHeaderToolbarElement;
    }
}
declare namespace LocalJSX {
    interface AppHeaderToolbar {
        "backCallback"?: Function;
        "headerTitle"?: string;
        "onCloseClicked"?: (event: CustomEvent<any>) => void;
        "showBack"?: boolean;
        "showClose"?: boolean;
        "showMenu"?: boolean;
    }
    interface AppHome {
    }
    interface AppRoot {
        "onDarkThemeEnabledChanged"?: (event: CustomEvent<any>) => void;
    }
    interface ModalHeaderToolbar {
        "backCallback"?: Function;
        "headerTitle"?: string;
    }
    interface IntrinsicElements {
        "app-header-toolbar": AppHeaderToolbar;
        "app-home": AppHome;
        "app-root": AppRoot;
        "modal-header-toolbar": ModalHeaderToolbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-header-toolbar": LocalJSX.AppHeaderToolbar & JSXBase.HTMLAttributes<HTMLAppHeaderToolbarElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "modal-header-toolbar": LocalJSX.ModalHeaderToolbar & JSXBase.HTMLAttributes<HTMLModalHeaderToolbarElement>;
        }
    }
}
