/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Note } from "./interfaces/application";
export namespace Components {
    interface AppHeaderToolbar {
        "backCallback": Function;
        "headerTitle": string;
        "showBack": boolean;
        "showClose": boolean;
        "showMenu": boolean;
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface ChordBox {
        "chordName": string;
        "chordNotes": Note[];
        "chordNumber": string;
    }
    interface CollapsiCard {
        "cardTitle": string;
        "collapsed": boolean;
    }
    interface KeyChords {
    }
    interface KeyNotes {
    }
    interface KeyScaleSelector {
    }
    interface ModalHeaderToolbar {
        "backCallback": Function;
        "headerTitle": string;
    }
    interface NoteBox {
        "boxColor": string;
        "isDiatonic": boolean;
        "isEmphasized": boolean;
        "isHighlighted": boolean;
        "isSelected": boolean;
        "noteName": string;
        "noteNumber": string;
        "noteSubtext": string;
    }
    interface PopoverMenu {
        "content": any;
    }
}
declare global {
    interface HTMLAppHeaderToolbarElement extends Components.AppHeaderToolbar, HTMLStencilElement {
    }
    var HTMLAppHeaderToolbarElement: {
        prototype: HTMLAppHeaderToolbarElement;
        new (): HTMLAppHeaderToolbarElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLChordBoxElement extends Components.ChordBox, HTMLStencilElement {
    }
    var HTMLChordBoxElement: {
        prototype: HTMLChordBoxElement;
        new (): HTMLChordBoxElement;
    };
    interface HTMLCollapsiCardElement extends Components.CollapsiCard, HTMLStencilElement {
    }
    var HTMLCollapsiCardElement: {
        prototype: HTMLCollapsiCardElement;
        new (): HTMLCollapsiCardElement;
    };
    interface HTMLKeyChordsElement extends Components.KeyChords, HTMLStencilElement {
    }
    var HTMLKeyChordsElement: {
        prototype: HTMLKeyChordsElement;
        new (): HTMLKeyChordsElement;
    };
    interface HTMLKeyNotesElement extends Components.KeyNotes, HTMLStencilElement {
    }
    var HTMLKeyNotesElement: {
        prototype: HTMLKeyNotesElement;
        new (): HTMLKeyNotesElement;
    };
    interface HTMLKeyScaleSelectorElement extends Components.KeyScaleSelector, HTMLStencilElement {
    }
    var HTMLKeyScaleSelectorElement: {
        prototype: HTMLKeyScaleSelectorElement;
        new (): HTMLKeyScaleSelectorElement;
    };
    interface HTMLModalHeaderToolbarElement extends Components.ModalHeaderToolbar, HTMLStencilElement {
    }
    var HTMLModalHeaderToolbarElement: {
        prototype: HTMLModalHeaderToolbarElement;
        new (): HTMLModalHeaderToolbarElement;
    };
    interface HTMLNoteBoxElement extends Components.NoteBox, HTMLStencilElement {
    }
    var HTMLNoteBoxElement: {
        prototype: HTMLNoteBoxElement;
        new (): HTMLNoteBoxElement;
    };
    interface HTMLPopoverMenuElement extends Components.PopoverMenu, HTMLStencilElement {
    }
    var HTMLPopoverMenuElement: {
        prototype: HTMLPopoverMenuElement;
        new (): HTMLPopoverMenuElement;
    };
    interface HTMLElementTagNameMap {
        "app-header-toolbar": HTMLAppHeaderToolbarElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "chord-box": HTMLChordBoxElement;
        "collapsi-card": HTMLCollapsiCardElement;
        "key-chords": HTMLKeyChordsElement;
        "key-notes": HTMLKeyNotesElement;
        "key-scale-selector": HTMLKeyScaleSelectorElement;
        "modal-header-toolbar": HTMLModalHeaderToolbarElement;
        "note-box": HTMLNoteBoxElement;
        "popover-menu": HTMLPopoverMenuElement;
    }
}
declare namespace LocalJSX {
    interface AppHeaderToolbar {
        "backCallback"?: Function;
        "headerTitle"?: string;
        "onCloseClicked"?: (event: CustomEvent<any>) => void;
        "showBack"?: boolean;
        "showClose"?: boolean;
        "showMenu"?: boolean;
    }
    interface AppHome {
    }
    interface AppRoot {
        "onDarkThemeEnabledChanged"?: (event: CustomEvent<any>) => void;
    }
    interface ChordBox {
        "chordName"?: string;
        "chordNotes"?: Note[];
        "chordNumber"?: string;
    }
    interface CollapsiCard {
        "cardTitle"?: string;
        "collapsed"?: boolean;
    }
    interface KeyChords {
    }
    interface KeyNotes {
    }
    interface KeyScaleSelector {
        "onKeyAlterationChanged"?: (event: CustomEvent<any>) => void;
        "onKeyChanged"?: (event: CustomEvent<any>) => void;
        "onScaleChanged"?: (event: CustomEvent<any>) => void;
    }
    interface ModalHeaderToolbar {
        "backCallback"?: Function;
        "headerTitle"?: string;
    }
    interface NoteBox {
        "boxColor"?: string;
        "isDiatonic"?: boolean;
        "isEmphasized"?: boolean;
        "isHighlighted"?: boolean;
        "isSelected"?: boolean;
        "noteName"?: string;
        "noteNumber"?: string;
        "noteSubtext"?: string;
        "onNoteDeselected"?: (event: CustomEvent<any>) => void;
        "onNoteSelected"?: (event: CustomEvent<any>) => void;
    }
    interface PopoverMenu {
        "content"?: any;
    }
    interface IntrinsicElements {
        "app-header-toolbar": AppHeaderToolbar;
        "app-home": AppHome;
        "app-root": AppRoot;
        "chord-box": ChordBox;
        "collapsi-card": CollapsiCard;
        "key-chords": KeyChords;
        "key-notes": KeyNotes;
        "key-scale-selector": KeyScaleSelector;
        "modal-header-toolbar": ModalHeaderToolbar;
        "note-box": NoteBox;
        "popover-menu": PopoverMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-header-toolbar": LocalJSX.AppHeaderToolbar & JSXBase.HTMLAttributes<HTMLAppHeaderToolbarElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "chord-box": LocalJSX.ChordBox & JSXBase.HTMLAttributes<HTMLChordBoxElement>;
            "collapsi-card": LocalJSX.CollapsiCard & JSXBase.HTMLAttributes<HTMLCollapsiCardElement>;
            "key-chords": LocalJSX.KeyChords & JSXBase.HTMLAttributes<HTMLKeyChordsElement>;
            "key-notes": LocalJSX.KeyNotes & JSXBase.HTMLAttributes<HTMLKeyNotesElement>;
            "key-scale-selector": LocalJSX.KeyScaleSelector & JSXBase.HTMLAttributes<HTMLKeyScaleSelectorElement>;
            "modal-header-toolbar": LocalJSX.ModalHeaderToolbar & JSXBase.HTMLAttributes<HTMLModalHeaderToolbarElement>;
            "note-box": LocalJSX.NoteBox & JSXBase.HTMLAttributes<HTMLNoteBoxElement>;
            "popover-menu": LocalJSX.PopoverMenu & JSXBase.HTMLAttributes<HTMLPopoverMenuElement>;
        }
    }
}
